### ISSUE TITLE
Crash after selecting a profile

### ISSUE THREAD

**Issue by Soulou** [outscale-dev/osc-tui#74]
I tested this project by curiosity, but after having created a profile, the application crashed:

```
└> python --version
Python 3.8.10
```

```
Traceback (most recent call last):
  File "/home/leo/sources/osc-tui/osc_tui/main.py", line 94, in <module>
    sys.exit(main())
  File "/home/leo/sources/osc-tui/osc_tui/main.py", line 85, in main
    APP.run()
  File "/home/leo/sources/osc-tui/env/lib/python3.8/site-packages/npyscreen/apNPSApplication.py", line 30, in run
    return npyssafewrapper.wrapper(self.__remove_argument_call_main)
  File "/home/leo/sources/osc-tui/env/lib/python3.8/site-packages/npyscreen/npyssafewrapper.py", line 41, in wrapper
    wrapper_no_fork(call_function)
  File "/home/leo/sources/osc-tui/env/lib/python3.8/site-packages/npyscreen/npyssafewrapper.py", line 97, in wrapper_no_fork
    return_code = call_function(_SCREEN)    
  File "/home/leo/sources/osc-tui/env/lib/python3.8/site-packages/npyscreen/apNPSApplication.py", line 25, in __remove_argument_call_main
    return self.main()
  File "/home/leo/sources/osc-tui/env/lib/python3.8/site-packages/npyscreen/apNPSApplicationManaged.py", line 172, in main
    self._THISFORM.edit()
  File "/home/leo/sources/osc-tui/env/lib/python3.8/site-packages/npyscreen/fm_form_edit_loop.py", line 47, in edit
    self.edit_loop()
  File "/home/leo/sources/osc-tui/env/lib/python3.8/site-packages/npyscreen/fm_form_edit_loop.py", line 38, in edit_loop
    self._widgets__[self.editw].edit()
  File "/home/leo/sources/osc-tui/env/lib/python3.8/site-packages/npyscreen/wgwidget.py", line 447, in edit
    self._edit_loop()
  File "/home/leo/sources/osc-tui/env/lib/python3.8/site-packages/npyscreen/wgwidget.py", line 463, in _edit_loop
    self.get_and_use_key_press()
  File "/home/leo/sources/osc-tui/env/lib/python3.8/site-packages/npyscreen/wgwidget.py", line 599, in get_and_use_key_press
    self.handle_input(ch)
  File "/home/leo/sources/osc-tui/env/lib/python3.8/site-packages/npyscreen/wgwidget.py", line 71, in handle_input
    self.handlers[_input](_input)
  File "/home/leo/sources/osc-tui/env/lib/python3.8/site-packages/npyscreen/wgbutton.py", line 99, in h_toggle
    self.whenPressed()
  File "/home/leo/sources/osc-tui/osc_tui/profileSelector.py", line 43, in __call__
    main.GATEWAY.log.config(type=LOG_MEMORY, what=LOG_KEEP_ONLY_LAST_REQ)
AttributeError: 'compiled_function' object has no attribute 'config'
```

Is it something known? 

Credentials set in the profile are working elsewhere.

Thanks!

**Comment by outscale-mgo** [comment]
Yes, osc_sdk_python introduce a log class in version 0.14.0, and osc-tui fail here because your osc_sdk_python is too old.

though not checking the osc_sdk_python version is a bug on osc-tui which should now be fix on master.

**Comment by Soulou** [comment]
I confirm it works now.
